package com.superman.superman.dao;

import com.superman.superman.model.HotUser;

public interface HotUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_user
     *
     * @mbggenerated
     */
    int insert(HotUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_user
     *
     * @mbggenerated
     */
    int insertSelective(HotUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_user
     *
     * @mbggenerated
     */
    HotUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HotUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HotUser record);
}