package com.superman.superman.dao;

import com.superman.superman.model.Oder;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface OderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);
//    @Select("select * from oder where p_id = #{pid} and order_status in ('1','2','-1') ")

    @Select("select * from oder where p_id =#{pid} and order_status=#{status}  ORDER BY order_create_time sort ")
    List<Oder> queryPddOderList(@Param("pid") String id,@Param("status") Integer status,@Param("sort") String sort);



    @Select("select sum(promotion_amount)*#{score} from oder where p_id =#{id}")
    Integer sumMoneyForIdToScore(@Param("score") Double score,@Param("id") String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oder
     *
     * @mbggenerated
     */
    int insertSelective(Oder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oder
     *
     * @mbggenerated
     */
    Oder selectByPrimaryKey(Long id);


    
    List<Oder> selectAll(@Param("oder") Oder oder);

    Integer selectPid(String pid);
    Integer selectPidIn(@Param("list") List list);


}