package com.superman.superman.dao;

import com.superman.superman.model.Tboder;

import java.util.List;

public interface TboderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
    int insert(Tboder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
    Integer selectPidIn(List list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
    Tboder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tboder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tboder record);
}