package com.superman.superman.model;

import java.util.Date;

public class HotUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_user.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_user.loginName
     *
     * @mbggenerated
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_user.loginPwd
     *
     * @mbggenerated
     */
    private String loginpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_user.loginSecret
     *
     * @mbggenerated
     */
    private Long loginsecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_user.userSex
     *
     * @mbggenerated
     */
    private Integer usersex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_user.userScore
     *
     * @mbggenerated
     */
    private Integer userscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_user.userPhoto
     *
     * @mbggenerated
     */
    private String userphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_user.userStatus
     *
     * @mbggenerated
     */
    private Integer userstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_user.userTotalScore
     *
     * @mbggenerated
     */
    private Long usertotalscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_user.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_user.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_user.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_user.userPhone
     *
     * @mbggenerated
     */
    private String userphone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_user.id
     *
     * @return the value of hot_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_user.id
     *
     * @param id the value for hot_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_user.userName
     *
     * @return the value of hot_user.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_user.userName
     *
     * @param username the value for hot_user.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_user.loginName
     *
     * @return the value of hot_user.loginName
     *
     * @mbggenerated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_user.loginName
     *
     * @param loginname the value for hot_user.loginName
     *
     * @mbggenerated
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_user.loginPwd
     *
     * @return the value of hot_user.loginPwd
     *
     * @mbggenerated
     */
    public String getLoginpwd() {
        return loginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_user.loginPwd
     *
     * @param loginpwd the value for hot_user.loginPwd
     *
     * @mbggenerated
     */
    public void setLoginpwd(String loginpwd) {
        this.loginpwd = loginpwd == null ? null : loginpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_user.loginSecret
     *
     * @return the value of hot_user.loginSecret
     *
     * @mbggenerated
     */
    public Long getLoginsecret() {
        return loginsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_user.loginSecret
     *
     * @param loginsecret the value for hot_user.loginSecret
     *
     * @mbggenerated
     */
    public void setLoginsecret(Long loginsecret) {
        this.loginsecret = loginsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_user.userSex
     *
     * @return the value of hot_user.userSex
     *
     * @mbggenerated
     */
    public Integer getUsersex() {
        return usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_user.userSex
     *
     * @param usersex the value for hot_user.userSex
     *
     * @mbggenerated
     */
    public void setUsersex(Integer usersex) {
        this.usersex = usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_user.userScore
     *
     * @return the value of hot_user.userScore
     *
     * @mbggenerated
     */
    public Integer getUserscore() {
        return userscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_user.userScore
     *
     * @param userscore the value for hot_user.userScore
     *
     * @mbggenerated
     */
    public void setUserscore(Integer userscore) {
        this.userscore = userscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_user.userPhoto
     *
     * @return the value of hot_user.userPhoto
     *
     * @mbggenerated
     */
    public String getUserphoto() {
        return userphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_user.userPhoto
     *
     * @param userphoto the value for hot_user.userPhoto
     *
     * @mbggenerated
     */
    public void setUserphoto(String userphoto) {
        this.userphoto = userphoto == null ? null : userphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_user.userStatus
     *
     * @return the value of hot_user.userStatus
     *
     * @mbggenerated
     */
    public Integer getUserstatus() {
        return userstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_user.userStatus
     *
     * @param userstatus the value for hot_user.userStatus
     *
     * @mbggenerated
     */
    public void setUserstatus(Integer userstatus) {
        this.userstatus = userstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_user.userTotalScore
     *
     * @return the value of hot_user.userTotalScore
     *
     * @mbggenerated
     */
    public Long getUsertotalscore() {
        return usertotalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_user.userTotalScore
     *
     * @param usertotalscore the value for hot_user.userTotalScore
     *
     * @mbggenerated
     */
    public void setUsertotalscore(Long usertotalscore) {
        this.usertotalscore = usertotalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_user.createTime
     *
     * @return the value of hot_user.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_user.createTime
     *
     * @param createtime the value for hot_user.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_user.updateTime
     *
     * @return the value of hot_user.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_user.updateTime
     *
     * @param updatetime the value for hot_user.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_user.status
     *
     * @return the value of hot_user.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_user.status
     *
     * @param status the value for hot_user.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_user.userPhone
     *
     * @return the value of hot_user.userPhone
     *
     * @mbggenerated
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_user.userPhone
     *
     * @param userphone the value for hot_user.userPhone
     *
     * @mbggenerated
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone == null ? null : userphone.trim();
    }
}