package com.superman.superman.model;

import java.util.Date;

public class Oder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.order_sn
     *
     * @mbggenerated
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.goods_thumbnail_url
     *
     * @mbggenerated
     */
    private String goodsThumbnailUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.goods_quantity
     *
     * @mbggenerated
     */
    private Integer goodsQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.goods_price
     *
     * @mbggenerated
     */
    private Integer goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.order_amount
     *
     * @mbggenerated
     */
    private Integer orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.p_id
     *
     * @mbggenerated
     */
    private String pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.promotion_rate
     *
     * @mbggenerated
     */
    private Long promotionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.promotion_amount
     *
     * @mbggenerated
     */
    private Long promotionAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.order_status
     *
     * @mbggenerated
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.order_status_desc
     *
     * @mbggenerated
     */
    private String orderStatusDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.order_create_time
     *
     * @mbggenerated
     */
    private Long orderCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.order_pay_time
     *
     * @mbggenerated
     */
    private Long orderPayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.order_group_success_time
     *
     * @mbggenerated
     */
    private Long orderGroupSuccessTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.order_verify_time
     *
     * @mbggenerated
     */
    private Long orderVerifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.order_modify_at
     *
     * @mbggenerated
     */
    private Long orderModifyAt;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.id
     *
     * @return the value of oder.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.id
     *
     * @param id the value for oder.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.order_sn
     *
     * @return the value of oder.order_sn
     *
     * @mbggenerated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.order_sn
     *
     * @param orderSn the value for oder.order_sn
     *
     * @mbggenerated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.goods_id
     *
     * @return the value of oder.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.goods_id
     *
     * @param goodsId the value for oder.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.goods_name
     *
     * @return the value of oder.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.goods_name
     *
     * @param goodsName the value for oder.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.goods_thumbnail_url
     *
     * @return the value of oder.goods_thumbnail_url
     *
     * @mbggenerated
     */
    public String getGoodsThumbnailUrl() {
        return goodsThumbnailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.goods_thumbnail_url
     *
     * @param goodsThumbnailUrl the value for oder.goods_thumbnail_url
     *
     * @mbggenerated
     */
    public void setGoodsThumbnailUrl(String goodsThumbnailUrl) {
        this.goodsThumbnailUrl = goodsThumbnailUrl == null ? null : goodsThumbnailUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.goods_quantity
     *
     * @return the value of oder.goods_quantity
     *
     * @mbggenerated
     */
    public Integer getGoodsQuantity() {
        return goodsQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.goods_quantity
     *
     * @param goodsQuantity the value for oder.goods_quantity
     *
     * @mbggenerated
     */
    public void setGoodsQuantity(Integer goodsQuantity) {
        this.goodsQuantity = goodsQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.goods_price
     *
     * @return the value of oder.goods_price
     *
     * @mbggenerated
     */
    public Integer getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.goods_price
     *
     * @param goodsPrice the value for oder.goods_price
     *
     * @mbggenerated
     */
    public void setGoodsPrice(Integer goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.order_amount
     *
     * @return the value of oder.order_amount
     *
     * @mbggenerated
     */
    public Integer getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.order_amount
     *
     * @param orderAmount the value for oder.order_amount
     *
     * @mbggenerated
     */
    public void setOrderAmount(Integer orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.p_id
     *
     * @return the value of oder.p_id
     *
     * @mbggenerated
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.p_id
     *
     * @param pId the value for oder.p_id
     *
     * @mbggenerated
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.promotion_rate
     *
     * @return the value of oder.promotion_rate
     *
     * @mbggenerated
     */
    public Long getPromotionRate() {
        return promotionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.promotion_rate
     *
     * @param promotionRate the value for oder.promotion_rate
     *
     * @mbggenerated
     */
    public void setPromotionRate(Long promotionRate) {
        this.promotionRate = promotionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.promotion_amount
     *
     * @return the value of oder.promotion_amount
     *
     * @mbggenerated
     */
    public Long getPromotionAmount() {
        return promotionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.promotion_amount
     *
     * @param promotionAmount the value for oder.promotion_amount
     *
     * @mbggenerated
     */
    public void setPromotionAmount(Long promotionAmount) {
        this.promotionAmount = promotionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.order_status
     *
     * @return the value of oder.order_status
     *
     * @mbggenerated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.order_status
     *
     * @param orderStatus the value for oder.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.order_status_desc
     *
     * @return the value of oder.order_status_desc
     *
     * @mbggenerated
     */
    public String getOrderStatusDesc() {
        return orderStatusDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.order_status_desc
     *
     * @param orderStatusDesc the value for oder.order_status_desc
     *
     * @mbggenerated
     */
    public void setOrderStatusDesc(String orderStatusDesc) {
        this.orderStatusDesc = orderStatusDesc == null ? null : orderStatusDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.order_create_time
     *
     * @return the value of oder.order_create_time
     *
     * @mbggenerated
     */
    public Long getOrderCreateTime() {
        return orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.order_create_time
     *
     * @param orderCreateTime the value for oder.order_create_time
     *
     * @mbggenerated
     */
    public void setOrderCreateTime(Long orderCreateTime) {
        this.orderCreateTime = orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.order_pay_time
     *
     * @return the value of oder.order_pay_time
     *
     * @mbggenerated
     */
    public Long getOrderPayTime() {
        return orderPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.order_pay_time
     *
     * @param orderPayTime the value for oder.order_pay_time
     *
     * @mbggenerated
     */
    public void setOrderPayTime(Long orderPayTime) {
        this.orderPayTime = orderPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.order_group_success_time
     *
     * @return the value of oder.order_group_success_time
     *
     * @mbggenerated
     */
    public Long getOrderGroupSuccessTime() {
        return orderGroupSuccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.order_group_success_time
     *
     * @param orderGroupSuccessTime the value for oder.order_group_success_time
     *
     * @mbggenerated
     */
    public void setOrderGroupSuccessTime(Long orderGroupSuccessTime) {
        this.orderGroupSuccessTime = orderGroupSuccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.order_verify_time
     *
     * @return the value of oder.order_verify_time
     *
     * @mbggenerated
     */
    public Long getOrderVerifyTime() {
        return orderVerifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.order_verify_time
     *
     * @param orderVerifyTime the value for oder.order_verify_time
     *
     * @mbggenerated
     */
    public void setOrderVerifyTime(Long orderVerifyTime) {
        this.orderVerifyTime = orderVerifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.order_modify_at
     *
     * @return the value of oder.order_modify_at
     *
     * @mbggenerated
     */
    public Long getOrderModifyAt() {
        return orderModifyAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.order_modify_at
     *
     * @param orderModifyAt the value for oder.order_modify_at
     *
     * @mbggenerated
     */
    public void setOrderModifyAt(Long orderModifyAt) {
        this.orderModifyAt = orderModifyAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.createTime
     *
     * @return the value of oder.createTime
     *
     * @mbggenerated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.updateTime
     *
     * @return the value of oder.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.updateTime
     *
     * @param updatetime the value for oder.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.status
     *
     * @return the value of oder.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.status
     *
     * @param status the value for oder.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}