package com.superman.superman.model;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.Date;
@Setter
@Getter
@ToString
public class Tboder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.adzone_id
     *
     * @mbggenerated
     */
    private Long adzoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.adzone_name
     *
     * @mbggenerated
     */
    private String adzoneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.alipay_total_price
     *
     * @mbggenerated
     */
    private String alipayTotalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.commission
     *
     * @mbggenerated
     */
    private Double commission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.commission_rate
     *
     * @mbggenerated
     */
    private String commissionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.order_type
     *
     * @mbggenerated
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.item_title
     *
     * @mbggenerated
     */
    private String itemTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.item_num
     *
     * @mbggenerated
     */
    private Integer itemNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.num_iid
     *
     * @mbggenerated
     */
    private Long numIid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.pay_price
     *
     * @mbggenerated
     */
    private String payPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.price
     *
     * @mbggenerated
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.tk_status
     *
     * @mbggenerated
     */
    private Byte tkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.site_id
     *
     * @mbggenerated
     */
    private String siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.site_name
     *
     * @mbggenerated
     */
    private String siteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.total_commission_rate
     *
     * @mbggenerated
     */
    private String totalCommissionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.trade_id
     *
     * @mbggenerated
     */
    private Long tradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.trade_parent_id
     *
     * @mbggenerated
     */
    private Integer tradeParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.odercreate_time
     *
     * @mbggenerated
     */
    private Date odercreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tboder.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

}