package com.superman.superman.model;

import java.util.Date;

public class Userinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.loginName
     *
     * @mbggenerated
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.loginPwd
     *
     * @mbggenerated
     */
    private String loginpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.loginSecret
     *
     * @mbggenerated
     */
    private Long loginsecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userSex
     *
     * @mbggenerated
     */
    private Integer usersex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userScore
     *
     * @mbggenerated
     */
    private Integer userscore;
    private Integer roleId;

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userPhoto
     *
     * @mbggenerated
     */
    private String userphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userStatus
     *
     * @mbggenerated
     */
    private Integer userstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userTotalScore
     *
     * @mbggenerated
     */
    private Long usertotalscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.jdPid
     *
     * @mbggenerated
     */
    private String jdpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.pddPid
     *
     * @mbggenerated
     */
    private String pddpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.tbPid
     *
     * @mbggenerated
     */
    private Long tbpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.wphPid
     *
     * @mbggenerated
     */
    private String wphpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userPhone
     *
     * @mbggenerated
     */
    private String userphone;

    private Integer score;

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.wxOpenId
     *
     * @mbggenerated
     */
    private String wxopenid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userName
     *
     * @return the value of userinfo.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userName
     *
     * @param username the value for userinfo.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.loginName
     *
     * @return the value of userinfo.loginName
     *
     * @mbggenerated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.loginName
     *
     * @param loginname the value for userinfo.loginName
     *
     * @mbggenerated
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.loginPwd
     *
     * @return the value of userinfo.loginPwd
     *
     * @mbggenerated
     */
    public String getLoginpwd() {
        return loginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.loginPwd
     *
     * @param loginpwd the value for userinfo.loginPwd
     *
     * @mbggenerated
     */
    public void setLoginpwd(String loginpwd) {
        this.loginpwd = loginpwd == null ? null : loginpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.loginSecret
     *
     * @return the value of userinfo.loginSecret
     *
     * @mbggenerated
     */
    public Long getLoginsecret() {
        return loginsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.loginSecret
     *
     * @param loginsecret the value for userinfo.loginSecret
     *
     * @mbggenerated
     */
    public void setLoginsecret(Long loginsecret) {
        this.loginsecret = loginsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userSex
     *
     * @return the value of userinfo.userSex
     *
     * @mbggenerated
     */
    public Integer getUsersex() {
        return usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userSex
     *
     * @param usersex the value for userinfo.userSex
     *
     * @mbggenerated
     */
    public void setUsersex(Integer usersex) {
        this.usersex = usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userScore
     *
     * @return the value of userinfo.userScore
     *
     * @mbggenerated
     */
    public Integer getUserscore() {
        return userscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userScore
     *
     * @param userscore the value for userinfo.userScore
     *
     * @mbggenerated
     */
    public void setUserscore(Integer userscore) {
        this.userscore = userscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userPhoto
     *
     * @return the value of userinfo.userPhoto
     *
     * @mbggenerated
     */
    public String getUserphoto() {
        return userphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userPhoto
     *
     * @param userphoto the value for userinfo.userPhoto
     *
     * @mbggenerated
     */
    public void setUserphoto(String userphoto) {
        this.userphoto = userphoto == null ? null : userphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userStatus
     *
     * @return the value of userinfo.userStatus
     *
     * @mbggenerated
     */
    public Integer getUserstatus() {
        return userstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userStatus
     *
     * @param userstatus the value for userinfo.userStatus
     *
     * @mbggenerated
     */
    public void setUserstatus(Integer userstatus) {
        this.userstatus = userstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userTotalScore
     *
     * @return the value of userinfo.userTotalScore
     *
     * @mbggenerated
     */
    public Long getUsertotalscore() {
        return usertotalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userTotalScore
     *
     * @param usertotalscore the value for userinfo.userTotalScore
     *
     * @mbggenerated
     */
    public void setUsertotalscore(Long usertotalscore) {
        this.usertotalscore = usertotalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.jdPid
     *
     * @return the value of userinfo.jdPid
     *
     * @mbggenerated
     */
    public String getJdpid() {
        return jdpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.jdPid
     *
     * @param jdpid the value for userinfo.jdPid
     *
     * @mbggenerated
     */
    public void setJdpid(String jdpid) {
        this.jdpid = jdpid == null ? null : jdpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.pddPid
     *
     * @return the value of userinfo.pddPid
     *
     * @mbggenerated
     */
    public String getPddpid() {
        return pddpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.pddPid
     *
     * @param pddpid the value for userinfo.pddPid
     *
     * @mbggenerated
     */
    public void setPddpid(String pddpid) {
        this.pddpid = pddpid == null ? null : pddpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.tbPid
     *
     * @return the value of userinfo.tbPid
     *
     * @mbggenerated
     */
    public Long getTbpid() {
        return tbpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.tbPid
     *
     * @param tbpid the value for userinfo.tbPid
     *
     * @mbggenerated
     */
    public void setTbpid(Long tbpid) {
        this.tbpid = tbpid == null ? null : tbpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.wphPid
     *
     * @return the value of userinfo.wphPid
     *
     * @mbggenerated
     */
    public String getWphpid() {
        return wphpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.wphPid
     *
     * @param wphpid the value for userinfo.wphPid
     *
     * @mbggenerated
     */
    public void setWphpid(String wphpid) {
        this.wphpid = wphpid == null ? null : wphpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.createTime
     *
     * @return the value of userinfo.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.createTime
     *
     * @param createtime the value for userinfo.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.updateTime
     *
     * @return the value of userinfo.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.updateTime
     *
     * @param updatetime the value for userinfo.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.status
     *
     * @return the value of userinfo.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.status
     *
     * @param status the value for userinfo.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userPhone
     *
     * @return the value of userinfo.userPhone
     *
     * @mbggenerated
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userPhone
     *
     * @param userphone the value for userinfo.userPhone
     *
     * @mbggenerated
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone == null ? null : userphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.wxOpenId
     *
     * @return the value of userinfo.wxOpenId
     *
     * @mbggenerated
     */
    public String getWxopenid() {
        return wxopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.wxOpenId
     *
     * @param wxopenid the value for userinfo.wxOpenId
     *
     * @mbggenerated
     */
    public void setWxopenid(String wxopenid) {
        this.wxopenid = wxopenid == null ? null : wxopenid.trim();
    }
}